site_name: nixcv
site_url: https://nixcv.nix.みんな
repo_url: https://github.com/djacu/nixcv
repo_name: djacu/nixcv
edit_uri: tree/main/site

nav:
  - Home: index.md
  - Documentation:
    - documentation/index.md
  - Examples:
    - examples/index.md
    - examples/personal.md
    - examples/objective.md
    - examples/education.md
    - examples/experience.md
    - examples/skills.md
    - examples/bibliography.md
  - Options:
    - Top:
      - modules/top/nixcv.md
      - modules/top/cv.md
    - Sections:
      - modules/sections/section.md
      - modules/sections/personal.md
    - Lists:
      - modules/lists/itemlist.md
      - modules/lists/item.md
      - modules/lists/items.md
      - modules/lists/profile.md
    - Text:
      - modules/text/text.md
      - modules/text/paragraphs.md
    - Skills:
      - modules/skills/skills.md
      - modules/skills/skill.md
    - Bibliography:
      - modules/biblatex/bibliography.md
    - Templates:
      - modules/templates/templates.md
      - modules/templates/layout.md
    - TemplatesContent:
      - modules/templates/templatesContent.md
      - enumitem:
        - modules/enumitem/enumitem.md
        - modules/enumitem/newlist.md
        - modules/enumitem/setlist.md
      - environments:
        - modules/templates/newenvironment.md
      - latex:
        - modules/templates/rawlatex.md
      - packages:
        - modules/templates/packages.md
      - titlesec:
        - modules/titlesec/titleformat.md
    - Bibresources:
      - modules/biblatex/bibresources.md
      - modules/biblatex/online.md
  - Blog:
    - blog/index.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  features:
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

plugins: 
  - blog
    #- social
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/djacu
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.igl.ooo/@djacu
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dannbaker/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - toc:
      permalink: true
  - pymdownx.pathconverter:
      base_path: '' # default: ''
      relative_path: '' # default ''
      absolute: false # default: false
      tags: 'a script img link object embed'

extra_css:
  - stylesheets/extra.css
