site_name: nixcv
site_url: https://nixcv.nix.みんな
repo_url: https://github.com/djacu/nixcv
repo_name: djacu/nixcv
edit_uri: tree/main/site

nav:
  - Home: index.md
  - Documentation:
    - documentation/index.md
  - Blog:
    - blog/index.md

theme:
  name: material
  features:
    - content.action.view
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

plugins: 
  - blog
  - social

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/djacu
    - icon: fontawesome/brands/mastodon 
      link: https://mastodon.igl.ooo/@djacu
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/dannbaker/

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - toc:
      permalink: true
